class: notes
preamble: preamble.tex

section: Voting Theory
    file: lecture-1.tex
    file: lecture-2.tex
    file: lecture-3.tex
    file: lecture-4.tex
    file: lecture-5.tex
section: Weighted Voting
    file: lecture-6.tex
    file: lecture-7.tex
    file: lecture-8.tex
section: Apportionment
    file: lecture-9.tex
    file: lecture-10.tex
    file: lecture-11.tex
section: Fair Division
    file: lecture-12.tex
    file: lecture-13.tex
    file: lecture-14.tex
section: Review
    file: lecture-15.tex
section: Historical Counting Systems
    file: lecture-16.tex
    file: lecture-17.tex
    file: lecture-18.tex
    file: lecture-19.tex
section: Cryptography
    file: lecture-20.tex
    file: lecture-21.tex
    file: lecture-22.tex
    file: lecture-23.tex
    file: lecture-24.tex
    file: lecture-25.tex
